spring:
  # DataSource configuration for PostgreSQL on Render
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/levelup_gamer}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    lazy-initialization: false

server:
  port: ${PORT:8080}

logging:
  level:
    root: WARN
    '[cl.duoc.levelup]': INFO