spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

logging:
  level:
    '[org.springframework.web]': INFO
    '[cl.duoc.levelup]': INFO
    '[org.springframework.boot.actuator.endpoint.web]': DEBUG